### API FUNCIONÁRIO GET
GET http://localhost:8080/api/v1/funcionarios

### API FUNCIONÁRIO POST
POST http://localhost:8080/api/v1/funcionarios
Content-Type: application/json

{
    "nome": "Carlos Silva",
    "cpf": "123.456.789-00",
    "email": "carlossilva@gmail.com",
    "telefone": "+55 47 98765-4321",
    "endereco": "Rua Exemplo, 123",
    "cargo": "Gerente"
}

### API FUNCIONÁRIO PUT
PUT http://localhost:8080/api/v1/funcionarios/1
Content-Type: application/json

{
    "nome": "Carlos Silva Updated",
    "cpf": "123.456.789-00",
    "email": "carlossilva2@gmail.com",
    "telefone": "+55 47 98765-4321",
    "endereco": "Rua Exemplo, 123",
    "cargo": "Gerente Sênior"
}

### API FUNCIONÁRIO DELETE
DELETE http://localhost:8080/api/v1/funcionarios/1
